services:
  db:
    image: postgres:15
    container_name: lobbyregister_db
    env_file:
      - .env                                                                                                                                                                      
    command: >                                                                                                                                                                      
      postgres                                                                                                                                                                      
      -c shared_buffers=1GB                                                                                                                                                        ▄
      -c effective_cache_size=3GB                                                                                                                                                  █
      -c maintenance_work_mem=256MB                                                                                                                                                █
      -c checkpoint_completion_target=0.9                                                                                                                                          █
      -c wal_buffers=16MB                                                                                                                                                          █
      -c default_statistics_target=100                                                                                                                                             █
      -c random_page_cost=1.1                                                                                                                                                      █
      -c effective_io_concurrency=200                                                                                                                                              █
      -c work_mem=16MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\""]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  ingest:
    image: ghcr.io/dav354/lobbyregister-ingestor:latest
    container_name: lobbyregister_ingestor
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  adminer:
    image: adminer:latest
    container_name: lobbyregister_adminer
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:12.2
    container_name: lobbyregister_grafana
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3003:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  pg_data:
  grafana_data:
